openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /employees:
    get:
      responses:
        '200':      # Response
          description: OK
          content:  # Response body
            'application/json':  # Media type
               schema: 
                 $ref: '#/components/schemas/Employee'    # Reference to object definition
            'application/xml':   # Media type
               schema: 
                 $ref: '#/components/schemas/Employee'    # Reference to object definition
  /info/logo:
    get:
      responses:
        '200':           # Response
          description: OK
          content:       # Response body
            'image/*':   # Media type
               schema: 
                 type: string
                 format: binary
components:
  schemas:
    Employee:      # Object definition
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        fullTime: 
          type: boolean
